### Section A: Data Structures & Control Structures
##### 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.


In [21]:
list1 = [1,3,5,7,9]

list1.append(11) #adding a number at last
print(f'Append : {list1}')

list1.extend([13,15]) # adding multiple numbers
print(f'Extend : {list1}')

list1.insert(2,17) # adding numbers at a certain index
print(f'Insert : {list1}')

list1.remove(3) 
print(f'Remove : {list1}')

popped = list1.pop()
print(f'Pop : {popped}')

list1.clear()
print(f'Clear : {list1}')

list2 = [2,2,5,4,1]

counts = list2.count(2)
print(f'Count : {counts}')

list2.sort()
print(f'Sort : {list2}')

list2.reverse()
print(f'Reverse : {list2}')

Append : [1, 3, 5, 7, 9, 11]
Extend : [1, 3, 5, 7, 9, 11, 13, 15]
Insert : [1, 3, 17, 5, 7, 9, 11, 13, 15]
Remove : [1, 17, 5, 7, 9, 11, 13, 15]
Pop : 15
Clear : []
Count : 2
Sort : [1, 2, 2, 4, 5]
Reverse : [5, 4, 2, 2, 1]


##### 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [23]:
tup = ('Sri','Sai','Yagnik')
tup[1] = 'Perisetla'
print(tup)
### Explanation: It throws an errors because Tuple is immutable and cannot be changed

TypeError: 'tuple' object does not support item assignment

##### 3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [26]:
set1 = {1,2,2,3,3,3,4,4,4,4,5}
print(set1)
### Explanation: A set in Python is an unordered collection of unique elements.

{1, 2, 3, 4, 5}


##### 4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [29]:
dict1 = {'Name': 'sai yagnik','Age':21,'City': 'Banglore'}
print(f"Orignial Dictionary: {dict1}")

dict1['Age'] = 23
print(f"Updated Age: {dict1}")

dict1['Email'] = 'saiyagnik00@gmail.com'
print(f"Updated Dictionary: {dict1}")

Orignial Dictionary: {'Name': 'sai yagnik', 'Age': 21, 'City': 'Banglore'}
Updated Age: {'Name': 'sai yagnik', 'Age': 23, 'City': 'Banglore'}
Updated Dictionary: {'Name': 'sai yagnik', 'Age': 23, 'City': 'Banglore', 'Email': 'saiyagnik00@gmail.com'}


##### 5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [33]:
age = int(input("Enter the Age: "))
if age>=18:
    print("You are Eligible to Vote")
else:
    print("You are not Eligible to Vote")

Enter the Age:  19


You are Eligible to Vote


##### 6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [40]:
marks = int(input("Enter your Marks: "))
if(marks>=90):
    print("A")
elif(marks<90 and marks>=75):
    print("B")
elif(marks<75 and marks>=50):
    print("C")
else:
    print("Fail")

Enter your Marks:  49


Fail


##### 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [46]:
number = int(input("Enter the Number: "))
if(number>0 and number%2==0):
    print("The number is Positive and Even")
elif(number<0):
    print("The number is Negative")
elif(number==0):
    print("The number is zero")
else:
    print("The number is Positive but Odd")

Enter the Number:  15


The number is Positive but Odd


#### Section B: Numpy

##### 8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [51]:
import numpy as np

scalar = np.array(5)
print("Scalar: ",scalar)

oned_arr = np.array([4,2,3,1,5])
print("1 Dimensional Array: ",oned_arr)

twod_arr = np.array([[10,40,30],[20,60,50]])
print("2 Dimensional Array: \n",twod_arr)

Scalar:  5
1 Dimensional Array:  [4 2 3 1 5]
2 Dimensional Array: 
 [[10 40 30]
 [20 60 50]]


##### 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [54]:
array = np.random.randint(0,100,16).reshape(4,4)
print("4x4 Numpy array: \n", array)

4x4 Numpy array: 
 [[ 1 24 89 95]
 [17 59 71 43]
 [77 84 68 53]
 [43 62 58 85]]


##### 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [69]:
import pandas as pd

twod_arr = np.array([[1,4,3],[2,6,5],[8,7,9]])
print("NumPy Array:")
print(twod_arr)

df = pd.DataFrame(twod_arr,columns=['A','B','C'])
print("Data Frame:")
print(df)

NumPy Array:
[[1 4 3]
 [2 6 5]
 [8 7 9]]
Data Frame:
   A  B  C
0  1  4  3
1  2  6  5
2  8  7  9


#### Section C: Exploring Pandas

##### 11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [115]:
Data = {
    'Name': ['Perisetla','Sri','Sai','Yagnik','Abhi','Sri','Nunna','Ashu','Vasi','Nunna'],
    'Age': [21,20,30,21,18,20,14,16,25,14],
    'City': ['Nellore','Banglore','Hyderabad','Chennai','Mumbai','Banglore','Delhi','Pondi','Banglore','Delhi'], 
    'Salary': [50000,60000,np.nan,80000,55000,60000,60000,80000,np.nan,60000]    
}
df = pd.DataFrame(Data)
print("DataFrame:\n")
df

DataFrame:



Name  Age       City   Salary
0  Perisetla   21    Nellore  50000.0
1        Sri   20   Banglore  60000.0
2        Sai   30  Hyderabad      NaN
3     Yagnik   21    Chennai  80000.0
4       Abhi   18     Mumbai  55000.0
5        Sri   20   Banglore  60000.0
6      Nunna   14      Delhi  60000.0
7       Ashu   16      Pondi  80000.0
8       Vasi   25   Banglore      NaN
9      Nunna   14      Delhi  60000.0

In [116]:
print("DataFrame Info:\n")
df.info()

DataFrame Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [117]:
print("DataFrame Describe:\n")
df.describe()

DataFrame Describe:



Age        Salary
count  10.000000      8.000000
mean   19.900000  63125.000000
std     4.931757  10999.188282
min    14.000000  50000.000000
25%    16.500000  58750.000000
50%    20.000000  60000.000000
75%    21.000000  65000.000000
max    30.000000  80000.000000

In [118]:
print("Selected Columns Name and City: \n")
df[['Name','City']]

Selected Columns Name and City: 



Name       City
0  Perisetla    Nellore
1        Sri   Banglore
2        Sai  Hyderabad
3     Yagnik    Chennai
4       Abhi     Mumbai
5        Sri   Banglore
6      Nunna      Delhi
7       Ashu      Pondi
8       Vasi   Banglore
9      Nunna      Delhi

In [119]:
drop = df.drop(columns=['City'])
print("Dropping city: \n")
drop

Dropping city: 



Name  Age   Salary
0  Perisetla   21  50000.0
1        Sri   20  60000.0
2        Sai   30      NaN
3     Yagnik   21  80000.0
4       Abhi   18  55000.0
5        Sri   20  60000.0
6      Nunna   14  60000.0
7       Ashu   16  80000.0
8       Vasi   25      NaN
9      Nunna   14  60000.0

In [120]:
df.isnull().sum()

Name      0
Age       0
City      0
Salary    2
dtype: int64

In [121]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
print("Filling missing values in Salary column with the mean")
df

Filling missing values in Salary column with the mean


Name  Age       City   Salary
0  Perisetla   21    Nellore  50000.0
1        Sri   20   Banglore  60000.0
2        Sai   30  Hyderabad  63125.0
3     Yagnik   21    Chennai  80000.0
4       Abhi   18     Mumbai  55000.0
5        Sri   20   Banglore  60000.0
6      Nunna   14      Delhi  60000.0
7       Ashu   16      Pondi  80000.0
8       Vasi   25   Banglore  63125.0
9      Nunna   14      Delhi  60000.0

In [122]:
df.duplicated().sum()

2

In [124]:
duplicates = df.drop_duplicates()
print("Removed Duplicated Rows: \n")
duplicates

Removed Duplicated Rows: 



Name  Age       City   Salary
0  Perisetla   21    Nellore  50000.0
1        Sri   20   Banglore  60000.0
2        Sai   30  Hyderabad  63125.0
3     Yagnik   21    Chennai  80000.0
4       Abhi   18     Mumbai  55000.0
6      Nunna   14      Delhi  60000.0
7       Ashu   16      Pondi  80000.0
8       Vasi   25   Banglore  63125.0